### ISSUE TITLE
Nefunguje přístup na internet z wa-dev-docker00

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/pywb#2]
```[rudolf@wa-dev-docker00 ~]$ curl -v https://www.google.com
* Could not resolve host: www.google.com; Neznámá chyba
* Closing connection 0
curl: (6) Could not resolve host: www.google.com; Neznámá chyba```

**Comment by dragounv** [comment]
Nastavil jsem správné dns servery, mělo by to fungovat. Na Jenkins se dostanu jen mi furt hlásí že nemám práva.

**Comment by westfood** [comment]
Vytvořil jsem úkol pro při přidání do Jenkins úkol tady: https://github.com/orgs/WebarchivCZ/projects/2/views/1?pane=issue&itemId=21041561
dám vědět až to bude read plus vytvořím dokumetnaci jestli chybí
